version: 2
jobs:
  build-java-8:

    working_directory: ~/cassandra-backup-java-8

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: cassandra-backup-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cassandra-backup-{{ checksum "pom.xml" }}

      - run: (echo "${google_application_credentials}" > /tmp/gcp.json) && mvn clean install

      - store_test_results:
          path: ~/cassandra-backup/target/surefire-reports
  build-java-11:

    working_directory: ~/cassandra-backup-java-11

    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: cassandra-backup-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cassandra-backup-{{ checksum "pom.xml" }}

      # Cassandra 3.x does not run with Java 11 so we are running with Cassandra 4.0 as tests are running embedded Cassandra instance too
      - run: (echo "${google_application_credentials}" > /tmp/gcp.json) && mvn clean install -Dbackup.tests.cassandra.version=4.0-alpha4 -Djava.version=11

      - store_test_results:
          path: ~/cassandra-backup/target/surefire-reports

workflows:
  version: 2
  build:
    jobs:
      - build-java-8
      - build-java-11:
          requires:
            - build-java-8
